trigger:
  branches:
    include: [ "*" ]
  tags:
    include: [ "*" ]

pool:
  name: WS

resources:
  repositories:
  - repository: azureCI
    type: git
    name: azureCI
    
variables:
  COMPONENT: payment
    
stages: 
#- template: "codecheck.yml@azureCI"
#- template: "codeTest.yml@azureCI"
#- template: "python-az.yml@azureCI"
- template: "docker.yml@azureCI"  