apiVersion: v2
name: payment
description: A Helm payment for Kubernetes

# A payment can be either an 'application' or a 'library' payment.
#
# Application payments are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library payments provide useful utilities or functions for the payment developer. They're included as
# a dependency of application payments to inject those utilities and functions into the rendering
# pipeline. Library payments do not define any templates and therefore cannot be deployed.
type: application

# This is the payment version. This version number should be incremented each time you make changes
# to the payment and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
